# -*- coding: utf-8 -*-
"""Handwritten Digit Recognition on MNIST784.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PVrLZ2n3fG5OxePxVAUvsh0zxkUG7G9
"""

from sklearn.datasets import fetch_openml

mnist = fetch_openml('mnist_784')

x,y =mnist['data'], mnist['target']

x.shape

y.shape

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import matplotlib
import matplotlib.pyplot as plt

some_digit = x.iloc[36001]
some_digit_image = some_digit.values.reshape(28,28)

plt.imshow(some_digit_image, cmap = matplotlib.cm.binary, interpolation ="nearest")
plt.axis("off")

y[36001]

x_train = x[:60000]

x_test = x[60000:]

y_train = y[:60000]

y_test = y[60000:]

import numpy as np
shuffle_index = np.random.permutation(60000)
x_train,y_train = x_train.iloc[shuffle_index], y_train.iloc[shuffle_index]

"""# Creating a 2 Detector"""

y_train = y_train.astype(np.int8)
y_test= y_test.astype(np.int8)
y_train_2 = (y_train ==2)
y_test_2 = (y_test==2)

y_train

y_test_2

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(tol = 0.1)

clf.fit(x_train, y_train_2)

clf.predict([some_digit])

from sklearn.model_selection import cross_val_score
a = cross_val_score(clf,x_train,y_train_2,cv=3,scoring = "accuracy")

a.mean()